In [1]:
import os
from math import nan
import pandas as pd
pd.options.plotting.backend='plotly'

# Data viz

In [10]:
meas = pd.read_csv(r'data\polimi_impianto_4_all.csv',
                   comment='#',
                   sep=';',
                   index_col=0,
                   parse_dates=True).resample('1h').mean()

meas

                      Potenza  StatoOK  StatoEsclamativo  StatoX
Time
2017-01-01 00:00:00  0.020476     0.75              0.25     0.0
2017-01-01 01:00:00  0.021271     1.00              0.00     0.0
2017-01-01 02:00:00  0.021481     1.00              0.00     0.0
2017-01-01 03:00:00  0.021742     1.00              0.00     0.0
2017-01-01 04:00:00  0.021790     1.00              0.00     0.0
...                       ...      ...               ...     ...
2019-12-31 19:00:00  0.018678     1.00              0.00     0.0
2019-12-31 20:00:00  0.019027     1.00              0.00     0.0
2019-12-31 21:00:00  0.018754     1.00              0.00     0.0
2019-12-31 22:00:00  0.018998     1.00              0.00     0.0
2019-12-31 23:00:00  0.019084     1.00              0.00     0.0

[26280 rows x 4 columns]

In [11]:
clean = pd.read_csv(r'data\polimi_impianto_4_all_cleaned.csv',
                   comment='#',
                   index_col=0,
                   parse_dates=True)

clean

                      Potenza
Datetime
2017-01-01 00:00:00  0.021271
2017-01-01 01:00:00  0.021271
2017-01-01 02:00:00  0.021481
2017-01-01 03:00:00  0.021742
2017-01-01 04:00:00  0.021790
...                       ...
2019-12-31 19:00:00  0.018678
2019-12-31 20:00:00  0.019027
2019-12-31 21:00:00  0.018754
2019-12-31 22:00:00  0.018998
2019-12-31 23:00:00  0.019084

[26280 rows x 1 columns]

In [12]:
pd.concat((meas.Potenza.rename('Raw'),
           clean.Potenza.rename('Clean')),axis=1).plot()

# Correlations

In [93]:
emd = pd.read_csv('df_emd.csv',index_col=0,parse_dates=True)
emd.corr()[['Load']]

             Load
Load     1.000000
Persist  0.851136
Weekday -0.007777
IMF1     0.047041
IMF2     0.523374
IMF3     0.690621
IMF4     0.114318
IMF5     0.108495
IMF6     0.083427
IMF7     0.113419
IMF8     0.207965
IMF9     0.149736
IMF10    0.054383
IMF11    0.071946